global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/xx/xx/xx' # Slack webhook url

route:
  receiver: 'slack-notifications'
  #group_by : ['alertname']
  #group_wait: 10s
  #group_interval: 10s
  #repeat_interval: 10s
  #receiver: 'email'

receivers:
#- name: 'email'
#  email_configs:
#  - to: 'receiver_mail_id@gmail.com'
#    from: 'mail_id@gmail.com'
#    smarthost: stmp.gmail.com:587
#    auth_usename: 'mail_id@gmail.com'
#    auth_identity: 'mail_id@gmail.com'
#    auth_password: 'password'
#  inhibit_rules:
#  - source_math:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']
  - name: 'slack-notifications'
    slack_configs:
      - channel: 'test'
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
