rule_files:
  - "/etc/prometheus/rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
scrape_configs:
- job_name: 'blackbox'
  scrape_interval: 10s
  metrics_path: /probe
  static_configs:
    - targets:
      - https://biz.tpb.vn
      - https://ebank.tpb.vn
      - https://vcbdigibiz.vietcombank.com.vn
      - https://vcbdigibank.vietcombank.com.vn
      - https://smartbanking.bidv.com.vn
      - https://www.bidv.vn/iBank/MainEB.html
      - https://efast.vietinbank.vn
  params:
    module: [http_2xx]
  relabel_configs:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - source_labels: [ __param_target ]
      target_label: instance
    - target_label: __address__
      replacement: "blackbox_exporter:9115"
- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets: ['10.211.55.4:9100']

